// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestService.proto

package eu.matilda.service.test;

public final class TestService {
  private TestService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021TestService.proto\022\027eu.matilda.service." +
      "test\032\026test/PingMessage.proto\032\036test/PingM" +
      "essageResponse.proto2b\n\004Test\022Z\n\004ping\022$.e" +
      "u.matilda.service.test.PingMessage\032,.eu." +
      "matilda.service.test.PingMessageResponse" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          eu.matilda.service.test.PingMessageOuterClass.getDescriptor(),
          eu.matilda.service.test.PingMessageResponseOuterClass.getDescriptor(),
        }, assigner);
    eu.matilda.service.test.PingMessageOuterClass.getDescriptor();
    eu.matilda.service.test.PingMessageResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
