// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Service.proto

package eu.matilda.service.service1;

public final class Service1Service {
  private Service1Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025Service1Service.proto\022\033eu.matilda.serv" +
      "ice.service1\032!common/BasicResponseMessag" +
      "e.proto\032\034service1/CreateMessage.proto2i\n" +
      "\010Service1\022]\n\006create\022*.eu.matilda.service" +
      ".service1.CreateMessage\032\'.eu.matilda.com" +
      "mon.BasicResponseMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          eu.matilda.common.BasicResponseMessageOuterClass.getDescriptor(),
          eu.matilda.service.service1.CreateMessageOuterClass.getDescriptor(),
        }, assigner);
    eu.matilda.common.BasicResponseMessageOuterClass.getDescriptor();
    eu.matilda.service.service1.CreateMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
